### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by piever** [piever/hidden_state_task#1]
Umbrella issue to collect suggested improvements.

### Graphical improvements:

- [x] Better contour for progress bars and font to distinguish from background
- [ ] Frames for damaged/very damaged enemy ship/ player ship
- [x] Remove gitter from enemy
- [x] Smoother ship movement (decelerate)

### Sound improvements:

- [ ] Sound for charge up

### User friendliness:

- [ ] Insert your name and welcome/game over screen
- [ ] Intro story (can be as simple as in the README)
- [x] Explain controls in start menu
- [x] Add key to toggle windowed mode
- [x] Tutorial

### Game improvements:

- [x] Add shield against laser with transparency + lens shaders
- [ ] Patterns of blue/red bullets rather than random

### Bugfix:

- [x] Pressing `Esc` in pause mode behaves strangely

**Comment by Kronopt** [comment]
Some more ideas:
- Windowed mode
- More obvious shooting key (like spacebar), or at least show the controls at the beginning of the game or in the pause menu

**Comment by piever** [comment]
Windowed mode is actually already implemented: if you bring the mouse to the top left corner of the screen (at least on mac, maybe on a different OS it's on the right) you can close/minimize/resize the window. Spacebar may be taken as a key for the shield when it's implemented, still it's a good idea to show the controls in the pause menu.

**Comment by Kronopt** [comment]
On windows 7 there is no close/minimize/resize menu
